services:

  # HTTP server
  server:
    restart: always
    depends_on:
      - postgres
      - memcached

    build: .
    container_name: 'server'

    ports:
      - "8080:8080"

    networks:
      - local

    environment:
      # Host
      HOST_PORT: 8080

      # Enable environment mode
      ARGS: -env

      # Postgres
      POSTGRES_IP: postgres

      # Memcached
      MEMCACHED_IP: memcached



  # Memcached
  memcached:
    restart: always

    image: memcached
    container_name: 'memcached'

    networks:
      - local

  # Postgres
  postgres:
    restart: always

    image: 'postgres:latest'

    volumes:
      - "./sql/migrate-up.sql:/docker-entrypoint-initdb.d/migrate-up.sql"

    ports:
      - "5433:5433"

    networks:
      - local

    environment:
      POSTGRES_DB: oauth
      POSTGRES_USER: server
      POSTGRES_PASSWORD: M5F3wWtFxkQ8Ra4n

networks:
  local:
    driver: 'bridge'